// PrivacyPolicy.jsx
import React from "react";
import Navbar from "../navbar/Navbar";
import PhoneNavbar from "../navbar/PhoneNavbar";
import ModernNav from "../navbar/ModernNav";
import SimpleNav from "../navbar/SimpleNav";

const PrivacyPolicy = () => {
  return (
    <>
    <SimpleNav />
        <ModernNav />
    <main style={{ maxWidth: "800px", margin: "5rem auto", padding: "1rem", }}>
      <h1>Privacy Policy</h1>
      <p>Last updated: {new Date().toLocaleDateString()}</p>

      <p>
        This Privacy Policy explains how <strong>itsallpolitics.gr</strong> collects, uses, and protects your information when you
        visit our website.
      </p>

      <h2>1. Information We Collect</h2>
      <p>We collect information in the following ways:</p>
      <ul>
        <li>
          <strong>Information you provide directly</strong>, for example when you
          contact us by email or via a contact form (such as your name, email
          address, and any other information you choose to provide).
        </li>
        <li>
          <strong>Automatically collected information</strong>: when you visit our
          Website, certain information is automatically collected by our
          analytics tools, such as your IP address, browser type, pages visited,
          and time spent on the site.
        </li>
      </ul>

      <h2>2. Cookies and Similar Technologies</h2>
      <p>
        We use cookies and similar technologies to recognize your browser,
        analyze traffic, and understand how visitors use our Website.
      </p>
      <p>
        Cookies are small text files stored on your device. You can control or
        delete cookies through your browser settings. However, disabling cookies
        may affect the functionality of some parts of our Website.
      </p>

      <h3>Google Analytics</h3>
      <p>
        We use Google Analytics, a web analytics service provided by Google LLC
        ("Google"). Google Analytics uses cookies to help us analyze how users
        interact with the Website. The information generated by the cookie about
        your use of the Website (including your IP address) may be transmitted
        to and stored by Google on servers in various countries.
      </p>
      <p>
        We use this information to understand Website traffic and usage. Google
        may use this data in accordance with its own privacy policy.
      </p>
      <p>
        You can learn more about how Google uses data by visiting Google&apos;s
        policies, and you can opt-out of Google Analytics by using the Google
        Analytics opt-out browser add-on.
      </p>

      <h2>3. How We Use Your Information</h2>
      <p>We use the information we collect for purposes such as:</p>
      <ul>
        <li>Operating and maintaining the Website</li>
        <li>Analyzing usage and improving our content and services</li>
        <li>Responding to your inquiries and providing support</li>
        <li>Protecting the security and integrity of the Website</li>
      </ul>

      <h2>4. Legal Bases for Processing (if you are in the EU/EEA)</h2>
      <p>
        If you are located in the European Economic Area (EEA), our legal bases
        for processing your personal data may include:
      </p>
      <ul>
        <li>
          <strong>Consent</strong> (for example, when you accept analytics cookies)
        </li>
        <li>
          <strong>Legitimate interests</strong> (for example, to maintain and improve
          the Website)
        </li>
        <li>
          <strong>Compliance with legal obligations</strong>
        </li>
      </ul>

      <h2>5. How We Share Your Information</h2>
      <p>
        We do not sell your personal data. We may share information with trusted
        service providers who help us operate the Website (such as analytics
        providers), but only to the extent necessary for them to provide their
        services and subject to appropriate safeguards.
      </p>

      <h2>6. Data Retention</h2>
      <p>
        We keep your information only for as long as necessary for the purposes
        described in this Privacy Policy, unless a longer retention period is
        required or permitted by law.
      </p>

      <h2>7. Your Rights</h2>
      <p>
        Depending on your location, you may have certain rights regarding your
        personal data, such as:
      </p>
      <ul>
        <li>The right to access the data we hold about you</li>
        <li>The right to request correction or deletion of your data</li>
        <li>
          The right to object to or restrict certain types of processing
        </li>
        <li>
          The right to withdraw consent (where processing is based on consent)
        </li>
      </ul>
      <p>
        To exercise these rights, please contact us using the details below.
      </p>

      <h2>8. Security</h2>
      <p>
        We take reasonable technical and organizational measures to protect your
        information from unauthorized access, loss, misuse, or alteration.
        However, no method of transmission over the Internet or electronic
        storage is 100% secure.
      </p>

      <h2>9. Third-Party Links</h2>
      <p>
        Our Website may contain links to third-party websites that are not
        operated by us. We are not responsible for the privacy practices or
        content of those sites. We encourage you to review the privacy policies
        of any third-party sites you visit.
      </p>

      <h2>10. Children&apos;s Privacy</h2>
      <p>
        Our Website is not directed to children under the age of 16, and we do
        not knowingly collect personal data from children. If you believe that a
        child has provided us with personal information, please contact us so we
        can remove it.
      </p>

      <h2>11. Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Any changes will be
        posted on this page with an updated "Last updated" date. We encourage
        you to review this page periodically.
      </p>

      <h2>12. Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy or how we handle
        your data, please contact us at:
      </p>
      <p>
        <strong>Email:</strong> itsallpolitics2023@gmail.com
        <br />
      </p>
    </main>
    </>
  );
};

export default PrivacyPolicy;
